config/routes.rb
Rails.application.routes.draw do

root "sessions#index"

get '/login', to: "sessions#login", as: 'login'
post '/login', to: "sessions#attempt_login"
delete '/logout', to: "sessions#logout", as: 'logout'
get '/signup', to: "users#signup", as: 'signup'
get '/home', to: "sessions#index", as: 'home'
post '/signup', to: "users#create"

  resources :users, except: ['index', 'new'] do
    resources :snippets, shallow: true
  end
  # resources :users, only: [] do
  #   resources :favorites, except: ['show']
  # end


end

app/models/editor.rb
class Editor < ActiveRecord::Base
  has_many :snippets
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :snippets
  validates :mode, :name, presence: true
  validates :name, uniqueness: true

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :user
  has_many :languages
  validates :name, :description, :code, :language_id, :editor_id, presence: true
  validates :code, uniqueness: true
  validates :name,  length: { in: 1..20 }
  validates :description,  length: { in: 10..140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, :email, :password, presence: true
  validates :username, :email, uniqueness: true
  validates :username, :password, length: { in: 6..10 }

  has_many :snippets
  # has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def prevent_login_signup
  	if session[:user_id]
  		redirect_to root_path, notice: "You are already logged in"
  	end
  end

	def confirm_logged_in
	   	 redirect_to login_path, alert: "Please Log In" unless session[:user_id]
	end

	def current_user
		return unless session[:user_id]
		@current_user ||= User.find_by_id(session[:user_id])
	end

  helper_method :current_user #this makes it available for the view

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def index
		@favorites = Favorite.all
		render :index
	end

	def create
		@favorite = Favorite.new(favorite_params)
		if @favorite.save
			redirect_to favorites_path, flash: {success: "Successfully Created!"}
		else
			render :new
		end
	end

	def update
		@favorite = Favorite.find params[:id]
		@favorite.update favorite_params
		redirect_to favorites_path
		if @favorite.save
			redirect_to favorite_path(@favorite), notice: "Updated"
		else
			render :edit
		end
	end

	def destroy
		@favorite = Favorite.find_by_id params[:id]
		@favorite.destroy
		redirect_to favorites_path
	end

	private

	def favorite_params
		params.require(:favorite).permit(:user_id, :snippet_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :prevent_login_signup, only: [:signup, :create, :login, :attempt_login]

  def index
    @snippets = Snippet.all

  end

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(username: params[:username]).first
      if found_user && found_user.authenticate(params[:password])
         session[:user_id] = found_user.id
         redirect_to root_path, flash: {notice: "Welcome back #{found_user.username}!"}
      else
        flash[:notice] = "Incorrect username or password"
        redirect_to login_path
      end
      else
        flash[:notice] = "Please enter valid username and password"
        redirect_to login_path
    end
  end

def logout
  session[:user_id] = nil
  flash[:notice] = "Logged Out"
  redirect_to login_path
end

private

def user_params
  params.require(:user).permit(
    :username,
    :email,
    :password
  )
end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
	def index
		@user = User.find params[:user_id]
		@snippets = @user.snippets
	end

	def new
		@user = User.find params[:user_id]
		@snippet = @user.snippets.new
		@languages = Language.all
		@editors = Editor.all
		# @user = User.first # this is only for tests
	end

	def create
		@user = User.find params[:user_id]
		@snippet = @user.snippets.new(snippet_params)
		@languages = Language.all
		@editors = Editor.all
		if @snippet.save
			redirect_to user_snippets_path params[:user_id]
		else
			render :new
		end
	end

	def show
		@snippet = Snippet.find params[:id]
		@user = User.find @snippet.user_id
		@language = Language.find @snippet.language_id
		@editor = Editor.find @snippet.editor_id
	end

	def edit

		@snippet = Snippet.find params[:id]
		@user = @snippet.user_id
		@languages = Language.all
		@editors = Editor.all
		@snippet = Snippet.find params[:id]
	end

	def update
		@snippet = Snippet.find params[:id]
		@user = @snippet.user_id
		@languages = Language.all
		@editors = Editor.all
		@snippet = Snippet.find params[:id]
		@snippet.update snippet_params
		if @snippet.save
			redirect_to user_snippets_path(@user)
		else
			render :new
		end
	end

	def destroy
		@snippet = Snippet.find params[:id]
		@user = @snippet.user_id
		@snippet.destroy
		redirect_to user_snippets_path(@user)
	end

	private

	def snippet_params
		params.require(:snippet).permit(:name, :code, :description, :user_id, :language_id, :editor_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :prevent_login_signup, only: [:create]

  def signup
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Successfully created!'
      redirect_to root_path
    else
      render :signup
    end
  end

  def edit
  end

  def update
    @user.update user_params
    if @user.save
      flash[:notice] = "Account updated"
    end
  end

  def delete
    @user = User.find params[:id]
    @user.destroy && session[:user_id] = nil
    flash[:notice] = "Account deleted, You have been logged out"
    redirect_to root_path
  end


  private


  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password
    )
  end

  def ensure_logged_in
    unless session[:id]
      redirect_to login_path, alert: "Please log in"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnippetShare.io</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
	<div class="col-md-12">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SnippetShare.io</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "All Snippets", root_path %></li>
      <li><a href="#">Popular</a></li>
      <li><a href="#">New</a></li>

      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search snippets..">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
				<% if current_user %>
					<li class="navbar-text"><%= image_tag("#{current_user.photo}", class: "img-rounded avatar") %></li>
					<li><a href="#">Welcome, <%= current_user.username %></a></li>
					<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add New Snippet", new_user_snippet_path(current_user) %></li>
            <li><%= link_to "View My Snippets", user_snippets_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Edit Account", edit_user_path(current_user)%></li>
          </ul>
        </li>
					<li><%= link_to "Logout", logout_path, method: :delete%></li>
				<% else %>
					<li><%= link_to "Login", login_path %></li>
				<% end %>
      </ul>
    </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
	<div class="col-md-12">
		<% flash.each do |key, value| %>
		  <% if key == "notice" %>
		    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
		  <% elsif key == "alert" %>
		    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
		  <% else %>
		    <%= content_tag :div, value, class: "text-center alert alert-success" %>
		  <% end %>
		<% end %>
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if instance.errors.any? %>
<div class="alert alert-danger" id="error_explanation">
  <h2><%= pluralize(instance.errors.count, "error") %>
    prohibited this
    <%= instance.class %>
    from being saved:</h2>
  <ul>
    <% instance.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div><% end %>

app/views/snippets/edit.html.erb
<% if @snippet.errors.any?%>
	<% @snippet.errors.full_messages.each do |e|%>
		<div class="alert alert-warning"><%= e %></div>
	<% end %>	
<% end %>
<%= link_to "Go Back", :back %><br>
<%= form_for @snippet, url: {action: "update"}, html:{class:"snippet_edit_form", role:"form"} do |f| %>
	<div class="form-group">
		<%= f.label "Snippet Name" %>
		<%= f.text_field :name, class:"form-control", autofocus: true %>
	</div>
	<div class="form-group">
		<%= f.label :description  %>
		<%= f.text_field :description, class:"form-control" %>
	</div>
	<div class="form-group">
	<%= f.label "Language: "  %> <%= f.collection_select(:language_id, @languages, :id, :name, :include_blank => true) %>
	<%= f.label "Editor: "  %> <%= f.collection_select(:editor_id, @editors, :id, :name, :include_blank => true) %>

	</div>
	<div class="form-group">
		<%= f.label :code  %>
		<%= f.text_area :code, id: "codemirror" , class: "form-control" %>
	</div>
	
	<div class="form-group actions">
		<%= f.submit class:"btn btn-primary" %>
	</div>
<% end %>
<%= button_to "Delete", snippet_path(@snippet), method: :delete, class: "btn btn-danger" %>

app/views/snippets/index.html.erb
<h1>View My Snippets</h1>

<% @snippets.each do |snippet| %>
<% @language = Language.find snippet.language_id  %>
<% @editor = Editor.find snippet.editor_id  %>
	<div class="col-md-4">
		<div class="snippet-card">
		<%= image_tag @language.icon, class: "icon" %>
			<div class="body">
				<h4 class="title"><%= link_to snippet.name, snippet_path(snippet) %></h4>
				<span class="description"><%= snippet.description %></span>
				<ul class="tags">
					<li><%= image_tag @editor.icon_src %>	<%= @editor.name %></li>
					<li><%= @language.name %></li>
				</ul>
			</div>
			<div class="meta">@<%= @user.username %></div>
		</div>
	</div>
<% end %>

app/views/snippets/new.html.erb
<% if @snippet.errors.any?%>
	<% @snippet.errors.full_messages.each do |e|%>
		<div class="alert alert-warning"><%= e %></div>
	<% end %>	
<% end %>

<%= form_for @snippet, url: user_snippets_path(@user), html:{class:"snippet_form", role:"form"} do |f| %>
	<div class="form-group">
		<%= f.label "Snippet Name" %>
		<p>Ex. 'if-else'</p>
		<%= f.text_field :name, class:"form-control", autofocus: true %>
	</div>
	<div class="form-group">
		<%= f.label :description  %>
		<p>Ex. 'must have x installed', 'creates a form'</p>
		<%= f.text_field :description, class:"form-control" %>
	</div>
	<div class="form-group">
	<%= f.label "Language: "  %> <%= f.collection_select(:language_id, @languages, :id, :name, :include_blank => true) %> 
	<%= f.label "Text editor: "  %> <%= f.collection_select(:editor_id, @editors, :id, :name, :include_blank => true) %>

	</div>
	<div class="form-group">
		<%= f.label :code  %>
		<%= f.text_area :code, id: "codemirror" , class: "form-control" %>
	</div>
	
	<div class="form-group actions">
		<%= f.submit class:"btn btn-primary" %>
	</div>
<% end %>

app/views/snippets/show.html.erb
<span><h1>Show Snippet</h1>
	<% if current_user = @user %>
		<%= link_to "Edit Snippet", edit_snippet_path(@snippet), class: "btn btn-success" %>
	<% end %>
	<%= link_to "Go Back", :back, class: "btn btn-default" %></span>

<div class="col-md-4">
		<div class="show-card">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Name</h3>
		  </div>
		  <div class="panel-body">
		    <h2><%= @snippet.name %></h2> <br>

		  </div>
		</div>
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Created by</h3>
		  </div>
		  <div class="panel-body">
		    @<%= @user.username %>
		  </div>
		</div>
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Description</h3>
		  </div>
		  <div class="panel-body">
		    <%= @snippet.description %>
		  </div>
		</div>
		<div class="row">
			<div class="col-sm-6">
				<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Editor</h3>
		  </div>
		  <div class="panel-body">
		    <table>
		   	<tr>
		   		<td> <%= @editor.name %> </td>
		   		<td><%= image_tag @editor.icon_src %></td>
		   	</tr>
		   </table>
		  </div>
		</div>
			</div>
			<div class="col-sm-6">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Language</h3>
		  </div>
		  <div class="panel-body">
		   <table>
		   	<tr>
		   		<td> <%= @language.name %> </td>
		   		<td><%= image_tag @language.icon %></td>
		   	</tr>
		   </table>
		  </div>
		</div>
		</div>
		</div>
		</div>



	</div>

		<%= text_area_tag nil, @snippet.code, id: "codemirror", readonly: true %>

app/views/users/edit.html.erb
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= form_for @user, url: {action: "update"}, html: {class: "edit-form"} do |f| %>
<%= render partial: "shared/errors", locals:{instance: @user} %>
<div class="form-group">
  <%= f.label :username, class: "control-label" %>
  <%= f.text_field :username, class: "form-control", required: true %>
</div>
<div class="form-group">
  <%= f.label :email, class: "control-label" %>
  <%= f.email_field :email, class: "form-control", required: true %>
</div>
<div class="form-group">
  <%= f.label :password, class: "control-label" %>
  <%= f.password_field :password, class: "form-control", required: true %>
</div>
<%= f.submit "Edit Info", id: "submit-user", class:"btn btn-block btn-success text-center" %>
<div class="form-group">
<% end %>

app/views/users/signup.html.erb
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if @user.errors.any?%>
  <% @user.errors.full_messages.each do |e|%>
    <div class="alert alert-warning"><%= e %></div>
  <% end %> 
<% end %>

<%= form_for @user, url: signup_path, html: {class: "signup-form"} do |f| %>
<%= render partial: "shared/errors", locals:{instance: @user} %>
<div class="form-group">
  <%= f.label :username, class: "control-label" %>
  <%= f.text_field :username, class: "form-control", required: true %>
</div>
<div class="form-group">
  <%= f.label :email, class: "control-label" %>
  <%= f.email_field :email, class: "form-control", required: true %>
</div>
<div class="form-group">
  <%= f.label :password, class: "control-label" %>
  <%= f.password_field :password, class: "form-control", required: true %>
</div>
<%= f.submit "Sign Up", id: "submit-user", class:"btn btn-block btn-success text-center" %>
<div class="form-group">
	<br>
	<p>Already an account? <%= link_to "Login here", login_path %></p>
</div>
<% end %>